In [16]:
import tensorflow as tf
print("Tensorflow version: ", tf.__version__)

Tensorflow version:  2.6.0


In [41]:
from PIL import Image as im
print(im.__version__)

8.3.2


In [61]:
mnist = tf.keras.datasets.mnist

# x_train = feature(s)
# y_train = label 
# Together = labeled example
(x_train_image, y_train), (x_test_image, y_test) = mnist.load_data()
x_train, x_test = x_train_image / 255.0, x_test_image / 255.0

In [73]:
image = im.fromarray(x_train_image[2])
image.show()
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [18]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [19]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.15717906,  0.31511104, -0.6231712 ,  0.00295383, -0.31877583,
        -0.38151196, -0.34240818,  0.23486343, -0.17973562,  0.43470392]],
      dtype=float32)

In [20]:
tf.nn.softmax(predictions).numpy()

array([[0.08968069, 0.14381754, 0.05627572, 0.10525525, 0.07629891,
        0.07165927, 0.07451692, 0.13272746, 0.08768044, 0.16208783]],
      dtype=float32)

In [21]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [22]:
loss_fn(y_train[:1], predictions).numpy()

2.6358328

In [23]:
model.compile(
    optimizer='adam',
    loss=loss_fn,
    metrics=['accuracy'])

In [24]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3016 - accuracy: 0.9121: 1s - loss: 0.6143 - accu - ETA: 1s - loss: 0.490 - E
Epoch 2/5
1875/1875 [==============================] - 2s 989us/step - loss: 0.1481 - accuracy: 0.9554
Epoch 3/5
1875/1875 [==============================] - 2s 963us/step - loss: 0.1144 - accuracy: 0.9658
Epoch 4/5
1875/1875 [==============================] - 2s 992us/step - loss: 0.0909 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 2s 974us/step - loss: 0.0779 - accuracy: 0.9755


In [25]:
model.evaluate(x_test, y_test, verbose = 2)

313/313 - 0s - loss: 0.0760 - accuracy: 0.9766


[0.07602034509181976, 0.9765999913215637]